### ISSUE TITLE
Active Directory domain support

### ISSUE THREAD

**Issue by danhale-git** [thycotic/tss-sdk-go#6]
I've used a Python example below because it's brief and complete:

	import requests
	import sys
	import getpass

	url = "https://mysecretserver"

	payload = {
	    "username": input("Enter username: "),
	    "password": getpass.getpass("Enter password: "),
	    "grant_type": "password",
	    "domain": "mydomain", # Necessary for this to work
	}

	res = requests.post(url + "/oauth2/token", payload, verify=False) 

	print(res.text)

This Python example works, tss-sdk-go does not. This is because I'm working with a Thycotic implementation where `"domain": "mydomain",` is required to obtain a token and tss-sdk-go does not include the `domain` field:
https://github.com/thycotic/tss-sdk-go/blob/fb180c0fea800dc6941365fd54e0cc8b002b480b/server/server.go#L131

Hard coding my domain into that request body causes authentication requests to return a token where previously they did not:

        body := strings.NewReader(url.Values{
		"username":   {s.Credentials.Username},
		"password":   {s.Credentials.Password},
		"domain":     {"mydomain"},
		"grant_type": {"password"},
	}.Encode())

**Comment by danhale-git** [comment]
Simple solution: https://github.com/thycotic/tss-sdk-go/pull/7

**Comment by amigus** [comment]
Fixed in #18
